export type PixelAssetKind = 'avatar' | 'object'
export type PixelDirection = 'down' | 'left' | 'up' | 'right'

export type PixelCatalogItem = {
  id: string
  kind: PixelAssetKind
  name: string
  category: string
  src: string
  width: number
  height: number
  price: number
  defaultUnlocked: boolean
  canSit?: boolean
  seatDirection?: PixelDirection
  /** Spritesheet clip region — when set, drawImage uses 9-arg form */
  frame?: { sx: number; sy: number; sw: number; sh: number; sheetW: number; sheetH: number }
}

export type PlacedRoomObject = {
  id: string
  itemId: string
  x: number
  y: number
  rotation: 0 | 1 | 2 | 3
}

export type PixelRoomState = {
  avatarId: string
  avatarX: number
  avatarY: number
  avatarDirection: PixelDirection
  isSitting: boolean
  sittingObjectId: string | null
  objects: PlacedRoomObject[]
  ownedItemIds: string[]
}

export const ROOM_COLUMNS = 26
export const ROOM_ROWS = 18
export const TILE_WIDTH = 32
export const TILE_HEIGHT = 32

export const DEFAULT_AVATAR_ID = 'default-avatar'

export const AVATAR_CATALOG: PixelCatalogItem[] = [
  {
    id: DEFAULT_AVATAR_ID,
    kind: 'avatar',
    name: 'Default Explorer',
    category: 'Default',
    src: '/pixel/game/avatars/light_graduation_black.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-braided-blue',
    kind: 'avatar',
    name: 'Braided Blue',
    category: 'Casual',
    src: '/pixel/game/avatars/light_braided_blue_yellow.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-formaldress-green',
    kind: 'avatar',
    name: 'Formal Dress Green',
    category: 'Formal',
    src: '/pixel/game/avatars/light_formaldress_green_orange.png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-formaldress-red',
    kind: 'avatar',
    name: 'Formal Dress Red',
    category: 'Formal',
    src: '/pixel/game/avatars/light_formaldress_red_brown.png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-graduation-gray',
    kind: 'avatar',
    name: 'Graduation Gray',
    category: 'Casual',
    src: '/pixel/game/avatars/light_graduation_gray.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-pkmn-black',
    kind: 'avatar',
    name: 'Trainer Black',
    category: 'Special',
    src: '/pixel/game/avatars/light_male_pkmn_black.png',
    width: 32,
    height: 32,
    price: 200,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-pkmn-blue',
    kind: 'avatar',
    name: 'Trainer Blue',
    category: 'Special',
    src: '/pixel/game/avatars/light_male_pkmn_blue.png',
    width: 32,
    height: 32,
    price: 200,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-pkmn-green',
    kind: 'avatar',
    name: 'Trainer Green',
    category: 'Special',
    src: '/pixel/game/avatars/light_male_pkmn_green.png',
    width: 32,
    height: 32,
    price: 200,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-pkmn-female',
    kind: 'avatar',
    name: 'Trainer White',
    category: 'Special',
    src: '/pixel/game/avatars/light_female_pkmn_white.png',
    width: 32,
    height: 32,
    price: 200,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-dark-jacket',
    kind: 'avatar',
    name: 'Casual Jacket',
    category: 'Casual',
    src: '/pixel/game/avatars/dark_casualjacket_blue_brown.png',
    width: 32,
    height: 32,
    price: 150,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-hijab-green',
    kind: 'avatar',
    name: 'Hijab Green',
    category: 'Casual',
    src: '/pixel/game/avatars/Neutral Casual Hijab - Green.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-hijab-yellow',
    kind: 'avatar',
    name: 'Hijab Yellow',
    category: 'Casual',
    src: '/pixel/game/avatars/Neutral Casual Hijab - Yellow.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-beard-green',
    kind: 'avatar',
    name: 'Casual Beard Green',
    category: 'Casual',
    src: '/pixel/game/avatars/Neutral Casual Beard - Green Red Brown.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-beard-red',
    kind: 'avatar',
    name: 'Casual Beard Red',
    category: 'Casual',
    src: '/pixel/game/avatars/Neutral Casual Beard - Red Yellow.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'avatar-halloween-mummy',
    kind: 'avatar',
    name: 'Mummy',
    category: 'Special',
    src: '/pixel/game/avatars/Halloween - Mummy.png',
    width: 32,
    height: 32,
    price: 300,
    defaultUnlocked: false,
  },
  {
    id: 'avatar-christmas-snowman',
    kind: 'avatar',
    name: 'Snowman',
    category: 'Special',
    src: '/pixel/game/avatars/Christmas - Snowman Purple.png',
    width: 32,
    height: 32,
    price: 300,
    defaultUnlocked: false,
  },
]

export const OBJECT_CATALOG: PixelCatalogItem[] = [
  // ── Office chairs spritesheet: rows = direction (down/left/up/right), cols = color ──
  ...((() => {
    const SHEET = '/pixel/core/chair_office_rolling.png'
    const FRAME = 32
    const COLORS = [
      { name: 'Dark Gray',  col: 0, price: 0,   unlocked: true  },
      { name: 'Gray',       col: 1, price: 0,   unlocked: true  },
      { name: 'White',      col: 2, price: 0,   unlocked: true  },
      { name: 'Orange',     col: 3, price: 100, unlocked: false },
      { name: 'Yellow',     col: 4, price: 100, unlocked: false },
      { name: 'Green',      col: 5, price: 100, unlocked: false },
      { name: 'Teal',       col: 6, price: 100, unlocked: false },
      { name: 'Blue',       col: 7, price: 100, unlocked: false },
      { name: 'Purple',     col: 8, price: 150, unlocked: false },
      { name: 'Dark Purple',col: 9, price: 150, unlocked: false },
    ]
    const DIRS: { label: string; row: number; dir: PixelDirection }[] = [
      { label: 'Down',  row: 0, dir: 'down'  },
      { label: 'Left',  row: 1, dir: 'left'  },
      { label: 'Up',    row: 2, dir: 'up'    },
      { label: 'Right', row: 3, dir: 'right' },
    ]
    const items: PixelCatalogItem[] = []
    for (const color of COLORS) {
      for (const d of DIRS) {
        items.push({
          id: `office-chair-${color.name.toLowerCase().replace(/\s/g, '-')}-${d.dir}`,
          kind: 'object',
          name: `${color.name} Chair (${d.label})`,
          category: 'Seating',
          src: SHEET,
          width: 32,
          height: 32,
          price: color.price,
          defaultUnlocked: color.unlocked && d.dir === 'down',
          canSit: true,
          seatDirection: d.dir,
          frame: { sx: color.col * FRAME, sy: d.row * FRAME, sw: FRAME, sh: FRAME, sheetW: COLORS.length * FRAME, sheetH: DIRS.length * FRAME },
        })
      }
    }
    return items
  })()),
  {
    id: 'plant-skinny-white',
    kind: 'object',
    name: 'Potted Plant',
    category: 'Decor',
    src: '/pixel/game/objects/plant_potted_skinny_white.png',
    width: 32,
    height: 64,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'desktop-set-white',
    kind: 'object',
    name: 'Desk Setup',
    category: 'Work',
    src: '/pixel/game/objects/desktop_set_white_down(1).png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'couch-purple',
    kind: 'object',
    name: 'Purple Couch',
    category: 'Lounge',
    src: '/pixel/game/objects/couch_purple_down.png',
    width: 128,
    height: 32,
    price: 0,
    defaultUnlocked: true,
    canSit: true,
    seatDirection: 'down',
  },
  {
    id: 'round-table-wood',
    kind: 'object',
    name: 'Round Table',
    category: 'Furniture',
    src: '/pixel/game/objects/table_simpleround_wood.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'bookshelf-bright',
    kind: 'object',
    name: 'Bookshelf',
    category: 'Storage',
    src: '/pixel/game/objects/bookshelf_darkwood_bright_2x2.png',
    width: 64,
    height: 64,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'desk-lamp',
    kind: 'object',
    name: 'Desk Lamp',
    category: 'Decor',
    src: '/pixel/game/objects/lamp_desk_down.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'pastel-rug',
    kind: 'object',
    name: 'Pastel Rug',
    category: 'Floor',
    src: '/pixel/game/objects/rug_needlepoint_pastelblue [4x4].png',
    width: 128,
    height: 128,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'coffee-mug',
    kind: 'object',
    name: 'Coffee Mug',
    category: 'Desk',
    src: '/pixel/game/objects/coffee_mug_white.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'monitor-up',
    kind: 'object',
    name: 'Monitor',
    category: 'Work',
    src: '/pixel/game/objects/monitor_up [1x1].png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'backpack-blue',
    kind: 'object',
    name: 'Blue Backpack',
    category: 'Personal',
    src: '/pixel/game/objects/backpack blue [1x1].png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
  {
    id: 'couch-lightbrown',
    kind: 'object',
    name: 'Light Brown Couch',
    category: 'Lounge',
    src: '/pixel/game/objects/couch_lightbrown_down.png',
    width: 128,
    height: 32,
    price: 150,
    defaultUnlocked: false,
    canSit: true,
    seatDirection: 'down',
  },
  {
    id: 'gamer-chair',
    kind: 'object',
    name: 'Gamer Chair',
    category: 'Seating',
    src: '/pixel/game/objects/gamer_chair.png',
    width: 32,
    height: 32,
    price: 200,
    defaultUnlocked: false,
    canSit: true,
    seatDirection: 'down',
  },
  {
    id: 'bamboo-chair',
    kind: 'object',
    name: 'Bamboo Chair',
    category: 'Seating',
    src: '/pixel/game/objects/bamboo_chair_woven_lightwood.png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
    canSit: true,
    seatDirection: 'down',
  },
  {
    id: 'bookshelf-alt',
    kind: 'object',
    name: 'Dark Bookshelf',
    category: 'Storage',
    src: '/pixel/game/objects/bookshelf_alt_wood_dark [3x2].png',
    width: 96,
    height: 64,
    price: 150,
    defaultUnlocked: false,
  },
  {
    id: 'laptop',
    kind: 'object',
    name: 'Laptop',
    category: 'Work',
    src: '/pixel/game/objects/laptop [1x2].png',
    width: 32,
    height: 64,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'globe',
    kind: 'object',
    name: 'Globe',
    category: 'Decor',
    src: '/pixel/game/objects/globe_teal_1.png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
  {
    id: 'piano',
    kind: 'object',
    name: 'Piano',
    category: 'Decor',
    src: '/pixel/game/objects/piano_inactive_down.png',
    width: 32,
    height: 32,
    price: 300,
    defaultUnlocked: false,
  },
  {
    id: 'fireplace-lit',
    kind: 'object',
    name: 'Fireplace',
    category: 'Decor',
    src: '/pixel/game/objects/fireplace_darkwood_lit.png',
    width: 32,
    height: 32,
    price: 250,
    defaultUnlocked: false,
  },
  {
    id: 'water-cooler',
    kind: 'object',
    name: 'Water Cooler',
    category: 'Office',
    src: '/pixel/game/objects/water_cooler.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'trash-black',
    kind: 'object',
    name: 'Trash Can',
    category: 'Office',
    src: '/pixel/game/objects/trash_black.png',
    width: 32,
    height: 32,
    price: 0,
    defaultUnlocked: true,
  },
  {
    id: 'gramaphone',
    kind: 'object',
    name: 'Gramophone',
    category: 'Decor',
    src: '/pixel/game/objects/gramaphone_1.png',
    width: 32,
    height: 32,
    price: 200,
    defaultUnlocked: false,
  },
  {
    id: 'backpack-red',
    kind: 'object',
    name: 'Red Backpack',
    category: 'Personal',
    src: '/pixel/game/objects/backpack red [1x1].png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
  {
    id: 'backpack-green',
    kind: 'object',
    name: 'Green Backpack',
    category: 'Personal',
    src: '/pixel/game/objects/backpack green [1x1].png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
  {
    id: 'rug-black',
    kind: 'object',
    name: 'Black Rug',
    category: 'Floor',
    src: '/pixel/game/objects/rug_needlepoint_black [4x4].png',
    width: 128,
    height: 128,
    price: 150,
    defaultUnlocked: false,
  },
  {
    id: 'rug-white',
    kind: 'object',
    name: 'White Rug',
    category: 'Floor',
    src: '/pixel/game/objects/rug_needlepoint_white [4x4].png',
    width: 128,
    height: 128,
    price: 150,
    defaultUnlocked: false,
  },
  {
    id: 'vending-machine',
    kind: 'object',
    name: 'Vending Machine',
    category: 'Office',
    src: '/pixel/game/objects/vending_machine_yellow_inactive [2x2].png',
    width: 64,
    height: 64,
    price: 400,
    defaultUnlocked: false,
  },
  {
    id: 'poster-cyberpunk',
    kind: 'object',
    name: 'Cyberpunk Poster',
    category: 'Decor',
    src: '/pixel/game/objects/poster_cyberpunk.png',
    width: 32,
    height: 32,
    price: 100,
    defaultUnlocked: false,
  },
]

export const PIXEL_CATALOG = [...AVATAR_CATALOG, ...OBJECT_CATALOG]

export function createDefaultRoomState(): PixelRoomState {
  return {
    avatarId: DEFAULT_AVATAR_ID,
    avatarX: Math.floor(ROOM_COLUMNS / 2),
    avatarY: Math.floor(ROOM_ROWS / 2),
    avatarDirection: 'down',
    isSitting: false,
    sittingObjectId: null,
    objects: [],
    ownedItemIds: PIXEL_CATALOG.filter((item) => item.defaultUnlocked).map((item) => item.id),
  }
}
