export interface Chat {
  id: string;
  name: string;
  avatar: string;
  lastMessage: string;
  timestamp: string;
  unread: number;
  isGroup: boolean;
  isPinned?: boolean;
  isMuted?: boolean;
  isOnline?: boolean;
  pinnedMessage?: string;
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  avatar: string;
  content: string;
  type: 'text' | 'image' | 'voice' | 'video';
  timestamp: string;
  isOwn: boolean;
  isRead: boolean;
  isDelivered: boolean;
  isEdited?: boolean;
  isForwarded?: boolean;
  isPinned?: boolean;
  reactions?: {
    emoji: string;
    count: number;
  }[];
  reply?: {
    senderName: string;
    content: string;
  };
  duration?: string;
}

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);

export const chatsData: Chat[] = [
  {
    id: 'alice',
    name: 'Alice Johnson',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    lastMessage: 'That sounds great! Let me check the designs...',
    timestamp: now.toISOString(),
    unread: 2,
    isGroup: false,
    isPinned: true,
    isOnline: true,
    pinnedMessage: 'Check out this design walkthrough!',
  },
  {
    id: 'design-team',
    name: 'Design Team',
    avatar: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=200&h=200&fit=crop',
    lastMessage: 'Anyone available for a quick sync?',
    timestamp: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    unread: 5,
    isGroup: true,
    isOnline: true,
  },
  {
    id: 'bob',
    name: 'Bob Smith',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    lastMessage: 'The API is ready for testing',
    timestamp: yesterday.toISOString(),
    unread: 0,
    isGroup: false,
    isMuted: true,
    isOnline: false,
  },
  {
    id: 'marketing',
    name: 'Marketing Sync',
    avatar: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=200&h=200&fit=crop',
    lastMessage: 'Campaign launch is scheduled for next week',
    timestamp: yesterday.toISOString(),
    unread: 0,
    isGroup: true,
    isOnline: true,
  },
  {
    id: 'sarah',
    name: 'Sarah Wilson',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    lastMessage: 'Can you review the latest mockup?',
    timestamp: twoDaysAgo.toISOString(),
    unread: 0,
    isGroup: false,
    isOnline: false,
  },
  {
    id: 'dev-chat',
    name: 'Dev Chat',
    avatar: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=200&h=200&fit=crop',
    lastMessage: 'Just merged the feature branch',
    timestamp: twoDaysAgo.toISOString(),
    unread: 0,
    isGroup: true,
    isOnline: false,
  },
];

export const messagesData: Record<string, Message[]> = {
  alice: [
    {
      id: '1',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Hey! How are you?',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 9 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '2',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Great! Just finished the component library',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 9 * 5 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '3',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Amazing! Can you share the link?',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 10 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '4',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'https://component-library.example.com',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 10 * 5 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '5',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Checking it out now... 🎉',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 10 * 10 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '6',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'The design is looking really polished!',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 14 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '7',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'https://images.unsplash.com/photo-1606348722273-d4fa5f00b4c5?w=400&h=300&fit=crop',
      type: 'image',
      timestamp: new Date(yesterday.getTime() + 14 * 5 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '8',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Those are some great mockups!',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 15 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
      reply: {
        senderName: 'Alice Johnson',
        content: 'https://images.unsplash.com/photo-1606348722273-d4fa5f00b4c5?w=400&h=300&fit=crop',
      },
    },
    {
      id: '9',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: '1:23',
      type: 'voice',
      timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '10',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'https://images.unsplash.com/photo-1633356122544-f134ef2e00a9?w=400&h=300&fit=crop',
      type: 'video',
      timestamp: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
      duration: '2:15',
    },
    {
      id: '11',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Check out this design walkthrough!',
      type: 'text',
      timestamp: new Date(now.getTime() - 43 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
      reactions: [
        { emoji: '👍', count: 1 },
        { emoji: '❤️', count: 1 },
      ],
    },
    {
      id: '12',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Amazing walkthrough! The transitions are smooth.',
      type: 'text',
      timestamp: new Date(now.getTime() - 35 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
      isEdited: true,
      reply: {
        senderName: 'Alice Johnson',
        content: 'Check out this design walkthrough!',
      },
    },
    {
      id: '13',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'That sounds great! Let me check the designs...',
      type: 'text',
      timestamp: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: false,
      isDelivered: true,
    },
    {
      id: '14',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&h=300&fit=crop',
      type: 'video',
      timestamp: new Date(now.getTime() - 25 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
      duration: '1:32',
    },
  ],
  'design-team': [
    {
      id: '1',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Just pushed the latest color system update',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 10 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '2',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Looking good! I have some feedback on the typography',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 11 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '3',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Let me know what you think! 👀',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 11 * 30 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '4',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'I think the spacing could be tighter on mobile',
      type: 'text',
      timestamp: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '5',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Good catch! Will adjust',
      type: 'text',
      timestamp: new Date(now.getTime() - 50 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '6',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Anyone available for a quick sync?',
      type: 'text',
      timestamp: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: false,
      isDelivered: true,
    },
  ],
  bob: [
    {
      id: '1',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Hey, completed the backend refactoring',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 14 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '2',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Awesome! Performance improvements?',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 14 * 5 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '3',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: '30% faster response times',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 9 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '4',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'That&apos;s fantastic!',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 10 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '5',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'The API is ready for testing',
      type: 'text',
      timestamp: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
  ],
  marketing: [
    {
      id: '1',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Q2 campaign strategy is ready for review',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 10 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '2',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Will review tonight',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 11 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '3',
      senderId: 'alice',
      senderName: 'Alice Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      content: 'Campaign launch is scheduled for next week',
      type: 'text',
      timestamp: new Date(yesterday.getTime() + 9 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
  ],
  sarah: [
    {
      id: '1',
      senderId: 'sarah',
      senderName: 'Sarah Wilson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      content: 'Hi! How&apos;s the project going?',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 9 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '2',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Great progress! Almost done with the MVP',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 10 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '3',
      senderId: 'sarah',
      senderName: 'Sarah Wilson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      content: 'Can you review the latest mockup?',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 14 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
  ],
  'dev-chat': [
    {
      id: '1',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Just finished the API integration',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 9 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '2',
      senderId: 'me',
      senderName: 'You',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Nice! Running tests now',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 10 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
      isRead: true,
      isDelivered: true,
    },
    {
      id: '3',
      senderId: 'bob',
      senderName: 'Bob Smith',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      content: 'Just merged the feature branch',
      type: 'text',
      timestamp: new Date(twoDaysAgo.getTime() + 14 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
      isRead: true,
      isDelivered: true,
    },
  ],
};
